[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.105.0",
    "anyio>=4.13.0",
    "boto3>=1.43.19",
    "fastapi>=0.136.3",
    "neo4j>=6.2.0",
    "numpy>=2.2.6",
    "openai>=2.38.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "redis>=8.0.0",
    "sse-starlette>=3.4.4",
]
